version: "3.7"
services:
  avalon:
    image: harbor.chlin.tk/vue/avalon:${TAG}
    container_name: avalon
    # environment:
    #   - PORT=22222
    volumes:
      - ~/volumes/avalon:/usr/src/app/logs
    restart: always
    ports: 
      - "${PORT}:${PORT}"
    env_file:
      - dev.env
    healthcheck:
      test: ["CMD", "curl", "-f", "127.0.0.1:${PORT}/healthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # networks:
    #   - docker-compose-base_default